default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: five_minutes_recipe_development

test:
  <<: *default
  database: five_minutes_recipe_test

production:
  <<: *default
  database: five_minutes_recipe_production
  username: root
  password: riri1053
  socket: /var/lib/mysql/mysql.sock